### ISSUE TITLE
计算的太慢！关键并不像说的那样那么好用~

### ISSUE THREAD

**Issue by weiyu666** [HsiaTsing/ProgressiveMeshes#1]
计算很慢，关键字什么的键盘事件不好用！
键“t”：显示/隐藏三角形边
键“c”：执行边折叠
键“s”：执行顶点分割
“z”键：面数减少5%
键“x”：与上述操作相反。
![图片](https://user-images.githubusercontent.com/22174508/95829390-c488ed80-0d68-11eb-894d-2c2a5c7cbcae.png)

**Comment by HsiaTsing** [comment]
> 计算很慢，关键字什么的键盘事件不好用！
> 键“t”：显示/隐藏三角形边
> 键“c”：执行边折叠
> 键“s”：执行顶点分割
> “z”键：面数减少5%
> 键“x”：与上述操作相反。
> ![图片](https://user-images.githubusercontent.com/22174508/95829390-c488ed80-0d68-11eb-894d-2c2a5c7cbcae.png)

1. 请用release模式编译，debug模式是用来调试的，速度慢很多；
2. 快捷键是在图形界面中使用的，不是在命令行里敲。。。

**Comment by weiyu666** [comment]
OK, thank you. I'll try
